{% set name = "sed-plume" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mcflugen/plume/archive/v{{ version }}.tar.gz
  sha256: 612f826390eda0379a74b26d1abbc8c4dbf7bff8f06bbae92d6e46098bc131f2

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3
  skip: true  # [py<39]
  entry_points:
    - plume = plume.cli:plume

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
    - cython
    - cythongsl
    - numpy
    - gsl
    - libopenblas  # [linux]
  run:
    - python
    - gsl
    - landlab >=2
    - pyyaml
    - rich-click
    - scipy
    - tomlkit

test:
  requires:
    - pip
  imports:
    - plume
  commands:
    - pip check
    - plume --version
    - plume --help
    - plume generate --help
    - plume run --help

about:
  home: https://github.com/mcflugen/plume
  summary: 'A hypopycnal sediment-carrying plume entering the ocean.'
  description: |
    A hypopycnal sediment-carrying plume entering the ocean.
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  doc_url: https://github.com/mcflugen/plume/blob/main/README.rst
  dev_url: https://github.com/mcflugen/plume

extra:
  recipe-maintainers:
    - mcflugen
